### PR TITLE
Add Hemaia Configs

### PR DESCRIPTION
**Pull request by rgantonio**
This PR adds other configurations for the Hemaia to avoid duplicating configs. As requested by @IveanEx for PR #329

### CODE REVIEW

**Comment by rgantonio** [comment]
@IveanEx , you mean cluster name needs to be same as the config name?

Like `snax_alu_cluster` name should be `snax_alu_cluster.hjson`?

**Comment by IveanEx** [comment]
> @IveanEx , you mean cluster name needs to be same as the config name?
> 
> Like `snax_alu_cluster` name should be `snax_alu_cluster.hjson`?

Yes indeed!

**Comment by rgantonio** [comment]
Ayayay

**Comment by rgantonio** [comment]
@IveanEx bump

**Review by IveanEx — APPROVED** [review]
Thanks @rgantonio !!!

**Pull request merged**
