### PR TITLE
Add busy io in streamer  code

### PR DESCRIPTION
**Pull request by xiaoling-yi**
In this PR, we add a busy read only csr in the streamer and update the related csr addresses in the sw test.

Please also check this issue: https://github.com/KULeuven-MICAS/snax_cluster/issues/177

### CODE REVIEW

**Review by JosseVanDelm — COMMENTED** [review]
@xiaoling-yi I'm not sure I understand what is happening here. IIRC there was no way to poll if the streamer was still busy. This seems to shift all streamer addresses (except for the alu?), but it does not adapt any of the wait routines to actually wait on the streamers, is that correct?

**Comment by xiaoling-yi** [comment]
Hi @JosseVanDelm , I add one busy state read-only CSR here for the streamer. Since the streamer CSR number changes, the later accelerator CSR address also changes. Please have a look at the alu example, that would be clear.

Now we have two mechanisms to check if the streamer finishes the data moving. 1) read the start CSR (it will block if the accelerator is busy (not ready in hardware)). 2) poll the busy state CSR.
In all the c runtime I wrote, 1) is used. In SNAX-ALU, 2) is used. You can choose one way you like to use it. :)

**Comment by JosseVanDelm** [comment]
> Hi @JosseVanDelm , I add one busy state read-only CSR here for the streamer. Since the streamer CSR number changes, the later accelerator CSR address also changes. Please have a look at the alu example, that would be clear.

Yes this is a bit annoying but definitely understandable and acceptable. No worries :slightly_smiling_face: 

> Now we have two mechanisms to check if the streamer finishes the data moving. 1) read the start CSR (it will block if the accelerator is busy (not ready in hardware)). 2) poll the busy state CSR. In all the c runtime I wrote, 1) is used. In SNAX-ALU, 2) is used. You can choose one way you like to use it. :)

I'm still a bit confused :smile:. The reason I discussed about #177 is because I was under the impression we should be waiting for both and not for either of these ready signals?

So IIUC you are suggesting:
**1)**
```c
void wait_for_gemm () {
    wait_for_accelerator();
}
```
or
**2)**
```c
void wait_for_gemm () {
    wait_for_streamer();
}
```
But I thought we would always need to:
**3)**
```c
void wait_for_gemm () {
    wait_for_accelerator();
    wait_for_streamer();
}
```
Because if I immediately relaunch an accelerator with new input data that is based on the old input data, won't the input streamers already start reading in the output data from the previous computation while that is not finished writing out yet?
So I would think that 2) is the safer option here (assuming output streamers will always be done later), and if that assumption does  not hold, then 3) is the most safe option?

I know this is an edge case, but i'd hate to debug this if this ever occurs

**Comment by xiaoling-yi** [comment]
Hi @JosseVanDelm , we actually use 3) already! We wait for both the streamer and the accelerator.

**Comment by xiaoling-yi** [comment]
Hi @rgantonio , with the busy io added in streamer, the CSR address also changes in the ALU example!

**Comment by xiaoling-yi** [comment]
Oh no, the hypercore's csr mapping also needs to be changed! @rgantonio We can have a look at this when you next week :)

**Comment by rgantonio** [comment]
Wait, am fixing the hypercorex haha

**Review by rgantonio — APPROVED** [review]
OK!

I made issue #246 and #247 to point out that we need to make the header files for the streamers instead.

So that we can avoid having to change ALL function numbers but rather change the header files. Take a look at the `hypercorex` header file. I just changed the header for the offset then everything is good! No need to offset each one.

Let's do it for the next PR. It will clean-up many things!

**Comment by rgantonio** [comment]
@xiaoling-yi feel-free to push if you want 😄

**Comment by rgantonio** [comment]
Oops! I mis clicked hahahaha

**Pull request merged**
