### PR TITLE
prepare for ubuntu & llvm bump

### PR DESCRIPTION
**Pull request by jorendumoulin**
FESVR version must be bumped to be compatible with new version of gcc: riscv-software-src/riscv-isa-sim#1284
llvm will be upgraded as well, I removed the version as symbolic links from llvm -> llvm-18 are placed by the container itself

### CODE REVIEW

**Comment by rgantonio** [comment]
Hmm I have a hunch why the wide-gemm fails. There are different make files happening to it... let me see what can be done in a different PR. I will make an issue for it.

**Review by rgantonio — APPROVED** [review]
OK! Re-run the failed wide-gemm and eventually it will succeed. 

Making issue for this intermittent fails. It did not fail for Hao's PR lastnight...

**Comment by jorendumoulin** [comment]
Okay thanks! The other error does seem related to the fesvr bump, I'll look into that

**Review by JosseVanDelm — APPROVED** [review]
Looks good!

**Pull request merged**
