### PR TITLE
Fix ALU test to pass

### PR DESCRIPTION
**Pull request by rgantonio**
This PR fixes the SNAX-ALU test for the system to pass CI.

Major TODOs:
- [x] Update ci
- [x] Add library name snax-alu
- [x] Add switchers to Makefiles
- [x] Update snax-alu.c program
- [x] Make library snxa-alu

### CODE REVIEW

**Comment by rgantonio** [comment]
@IveanEx or @xiaoling-yi please approve hehe this fixes the SNAX alu

**Review by IveanEx — APPROVED** [review]
Good!

**Comment by rgantonio** [comment]
Thank you @IveanEx !!!

**Comment by rgantonio** [comment]
> > Thank you @IveanEx !!!
> 
> Actually stack PR does not need us to approve haha you can directly merge, as you have the write access😂

AHA YES YOU'RE RIGHT LOL. Force of habit 🤡

**Pull request merged**
