### PR TITLE
[docker] add prebuilt images again and reduce image size

### PR DESCRIPTION
**Pull request by JosseVanDelm**
This PR redoes the work of #138 which was lost somewhere along the way

### CODE REVIEW

**Comment by jorendumoulin** [comment]
I fixed the errors by going back to using gcc for compiling the verilator model. I don't know why clang results in erroneous execution, but as the new gcc compiles fast enough, this is no big problem.

Additionally, I further reduced the size to 4.1GB by removing some cache and the custom llvm toolchain, as we don't need it (see kuleuven-micas/snax-mlir#130 for a successfull `snax-mlir` ci on this container image).

**Comment by jorendumoulin** [comment]
@rgantonio @JosseVanDelm 
For me this one is ready to go! It is mostly a copy of #138, but with all the problems resolved.
A big thank you to @JosseVanDelm on continuing this crusade in my absence.

**Comment by jorendumoulin** [comment]
I tried to request your review @JosseVanDelm but this is not possible as this is your PR 😆 .
Anyway, only thing left to do is also to convert the docker tags back to main

**Comment by JosseVanDelm** [comment]
Happy to self-accept this :+1:

**Review by rgantonio — APPROVED** [review]
It's good~

I just have a deep realization, but are you guys using the `snax-mac` and `snax-gemm` actually? haha

Right-now, it's like we just use those for testing if the platform is still working but we're not using them really for anything more useful.

**Comment by jorendumoulin** [comment]
yes haha we plan on removing them sooner rather than later, they are mostly old tests

**Pull request merged**
