### PR TITLE
Xyi/sw clean gemmx dr

### PR DESCRIPTION
**Pull request by xiaoling-yi**
Redundant software code is removed here following this PR: https://github.com/KULeuven-MICAS/snax_cluster/pull/270, including snax-gemm, snax-streamer-gemm, snax-streamer-simd, snax-streamer-gemm-add-c, snax-streamer-conv. These libs are now merged into the snax-streamer-gemm-conv-simd.

### CODE REVIEW

**Review by rgantonio — APPROVED** [review]
OK!

Are sure the other library files are not needed on your side anymore? This is totally fine with me 😄

**Comment by jorendumoulin** [comment]
Where is the `set_block_gemm_csr` now?

**Comment by xiaoling-yi** [comment]
> Where is the `set_block_gemm_csr` now?

It is removed. Now there is only one `set_gemmx_csr` for setting the csrs for the gemmx. 
Is anywhere the `set_block_gemm_csr` still be used on your side?

**Comment by jorendumoulin** [comment]
Yes, i thought we were going to keep streamer-gemm and streamer-gemm-add-c  for a little while until our tests have moved to the gemmx?

**Comment by xiaoling-yi** [comment]
Ok, I thought there was no one using it. Can you add whatever you need back? Since some useful functions have already been moved to snax-streamer-gemm-conv-simd from the streamer-gemm. Basically, I cleaned all the dead code that is not used in the current software test.

**Pull request merged**
