### PR TITLE
Clean-up double driven signal and declaration of generated directory

### PR DESCRIPTION
**Pull request by rgantonio**
This PR is a simple clean-up for the following:

- [x] Remove double-driven signal from the generated template. This was not captured in Verilator because Verilator assumes that the new assignment over-writes the initial assignment.
- [x] Add generated directory. This is for questa sim flow to work. It's a minor adjustment that just requires that the `/generated` directory needs to exist before writing the boot data and memories.

**Nothing changes functionally.**

### CODE REVIEW

**Review by IveanEx — APPROVED** [review]
I added the strb signal from Chisel side but not do the full cleaning on the wrappers 😂😂 Thanks for your fixing!

**Comment by rgantonio** [comment]
> I added the strb signal from Chisel side but not do the full cleaning on the wrappers 😂😂 Thanks for your fixing!

LOL so that's why haha ok ok!

**Comment by rgantonio** [comment]
@IveanEx I rebased it already. Gonna wait for it to be passing.

**Comment by rgantonio** [comment]
@IveanEx thanks for checking!

**Pull request merged**
