### PR TITLE
Add snax_disable_csr_manager option to disable csr manager generation

### LINKED ISSUE #190: Generate accelerator wrapper without a CSR manager
I would like to generate an accelerator wrapper without a CSR manager, as the accelerator handles the CSRs itself. To do this, the CSR control ports should be routed into the accelerator instead of the CSR manager. I tried setting the `snax_num_rw_csr` and `snax_num_ro_csr` to zero, however, this gives compile errors in the CSR manager.

While generating the template, there are two options to provide this bypass:
1. Detect when the `snax_num_*_csr` values are both zero.
2. Add a new config option (something like `snax_csr_manager_disable`)

Let me know what you think, I can provide a PR if you agree on one of the options!

### PR DESCRIPTION
**Pull request by RickLuiken**
Fixes #190 

I made sure that `snax_disable_csr_manager` is by default false. Also, `snax_num_rw_csr` and `snax_num_ro_csr` do not have to be set if `snax_disable_csr_manager` is set.

Let me know if you want to see anything added or changed!

### CODE REVIEW

**Comment by RickLuiken** [comment]
I fixed the python lint errors, but I'm not sure what went wrong with the bender vendor job. The other failed job might be #181?

**Review by xiaoling-yi — APPROVED** [review]

**Comment by xiaoling-yi** [comment]
Hi @RickLuiken , thanks for this PR! 👍  We can leave the wide-gemm ci failing. It happens randomly and we don't know why yet.

**Comment by JosseVanDelm** [comment]
@RickLuiken feel free to press the big green button! Or let me know if you're not able to (I don't think we have had many external contributions yet, so not sure how that would (not) work)

**Comment by RickLuiken** [comment]
Hi @JosseVanDelm!

No big green button for me :(
Even with changes being approved, you need write access to the repo. So, one of you should merge it

**Comment by JosseVanDelm** [comment]
Ok! Done!

**Pull request merged**
