### PR TITLE
Add `snax_mac` target to bender

### PR DESCRIPTION
**Pull request by rgantonio**
This PR cleans-up the bender to avoid adding the HWPE MAC to the filelist. It's a minor clean-up because it needed the `-target snax_mac` which was forgotten to be added.

### CODE REVIEW

**Comment by xiaoling-yi** [comment]
@rgantonio is anywhere still using the old hwpe mac?

**Comment by rgantonio** [comment]
> @rgantonio is anywhere still using the old hwpe mac?

OMG it shouldn't! Lemme check. But yes it shouldn't :(

**Comment by rgantonio** [comment]
> @rgantonio is anywhere still using the old hwpe mac?

Actually, no one is using it as far as I know? so I guess it's safe to take out?

**Comment by rgantonio** [comment]
@xiaoling-yi aha it's still being used in the docker haha let's leave it be until they take it out first 😄

**Comment by rgantonio** [comment]
@xiaoling-yi or @IveanEx someone plez approve? haha

**Comment by xiaoling-yi** [comment]
Ok!

**Review by xiaoling-yi — APPROVED** [review]

**Comment by rgantonio** [comment]
Thank youuu! @xiaoling-yi mwah! ❤️ ❤️ ❤️ ❤️ ❤️

**Pull request merged**
